server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/toysampletracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Ensure Hibernate does not modify schema for migrations purpose
  flyway:
    baseline-on-migrate: true
    baseline-version: 2
    enabled: true
    url: jdbc:postgresql://postgres-db:5432/toysampletracker
    user: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"