spring:
  profiles:
    active: local  # Default to 'local', but can be overridden
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
  logging:
    level:
      org.springframework: INFO
