server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/toysampletracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Ensure Hibernate does not modify schema for migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2
    url: jdbc:postgresql://postgres-db:5432/toysampletracker
    user: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: "*"

feature-flags:
  enable-sample-approval: ${FEATURE_ENABLE_SAMPLE_APPROVAL:false}