server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:toysampletracker;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console  # http://localhost:8082/h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:h2:mem:toysampletracker
    user: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
